# Generated by Django 5.0.1 on 2024-04-07 01:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questionStatement', models.TextField()),
                ('optionA', models.CharField(max_length=255)),
                ('optionB', models.CharField(max_length=255)),
                ('optionC', models.CharField(max_length=255)),
                ('optionD', models.CharField(max_length=255)),
                ('answer', models.CharField(choices=[('A', 'OPTION_A'), ('B', 'OPTION_B'), ('C', 'OPTION_C'), ('D', 'OPTION_D')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jobTitle', models.CharField(max_length=255)),
                ('jobDescription', models.TextField()),
                ('totalTime', models.IntegerField()),
                ('totalScore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('testTime', models.DateTimeField()),
                ('skills', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=15)),
                ('cvTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', models.JSONField()),
                ('cvScore', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('testScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('testId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revapp.test')),
            ],
        ),
    ]
