# Generated by Django 5.0.1 on 2024-04-07 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0006_user_otp'),
        ('revapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='testId',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='testScore',
        ),
        migrations.AddField(
            model_name='questions',
            name='testId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='revapp.test'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TestCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skills', models.JSONField()),
                ('testScore', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revapp.candidate')),
                ('testId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revapp.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authAPI.user')),
            ],
        ),
    ]
