# Generated by Django 5.0.1 on 2024-04-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revapp', '0002_remove_candidate_skills_remove_candidate_testid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcandidate',
            name='skills',
        ),
    ]
