# Generated by Django 5.0.1 on 2024-05-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revapp', '0003_remove_testcandidate_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
