# Generated by Django 5.0.1 on 2024-06-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revapp', '0005_candidate_recruiterid'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='testScore',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
